# Generated by Django 4.1.5 on 2023-01-20 10:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Текст отклика')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('heal', 'Хилы'), ('dd', 'ДД'), ('buyers', 'Торговцы'), ('guildmasters', 'Гилдмастера'), ('quest', 'Квестгиверы'), ('smith', 'Кузнецы'), ('tanner', 'Кожевенники'), ('potion', 'Зельевары'), ('spellmasters', 'Мастера заклинаний')], default='tanks', max_length=12, verbose_name='Категория')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
        ),
    ]
